development:
  adapter: mysql2
  database: montessori_from_birth_dev
  username: root
  password: lu253i
  pool: 5
  timeout: 5000

test:
  adapter: mysql2
  database: montessori_from_birth_test
  username: root
  password: lu253i
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: montessori_from_birth_prod
  username: root
  password: lu253i
  pool: 5
  timeout: 5000
